---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc-nfs-pvc1
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: vol
        mountPath: /datata


# kubectl exec -it ubuntu bash