---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: bob.psilva.org
    path: "/mnt/user/k8scached/pp"

