---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pvc1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-nfs1