---
- name: Initialize Kubernetes master with kubeadm init
  command: >
    kubeadm init \
    --pod-network-cidr=192.168.0.0/16 \
    --upload-certs \
    --control-plane-endpoint=kloadbalancer1.psilva.org
  register: kubeadmin_init

- name: Print the init output to screen.
  debug:
    var: kubeadmin_init.stdout

- name: Save output to ~/kube-join.txt
  copy: content="{{ kubeadmin_init.stdout }}" dest=~/kube-join.txt

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Copy kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    mode: u=rwx,g=rx,o=rx  # 755
    remote_src: true

- name: Configure Calico networking.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
    - kubectl apply -f https://docs.projectcalico.org/manifests/custom-resources.yaml
  register: calico_result
  changed_when: "'created' in calico_result.stdout"

- name: "Copy metallb configmap"
  ansible.builtin.copy:
    src: files
    dest: /tmp

- name: Configure Metal LoadBalancer
  command: "{{ item }}"
  with_items:
    - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/namespace.yaml
    - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/metallb.yaml
    - kubectl apply -f /tmp/files/metallb-configmap.yaml
    - kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  register: metallb_result
  changed_when: "'created' in metallb_result.stdout"

- name: Configure BOB as NFS Storage Class
  command: "{{ item }}"
  with_items:
    - kubectl apply -f /tmp/files/nfs-subdir-external-provisioner/rbac.yaml
    - kubectl apply -f /tmp/files/nfs-subdir-external-provisioner/class.yaml
    - kubectl apply -f /tmp/files/nfs-subdir-external-provisioner/deployment.yaml
  register: bob_nfs_config
  changed_when: "'created' in bob_nfs_config.stdout"
