---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rest2"
  namespace: "default"
  labels:
    app: "rest2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "rest2"
  template:
    metadata:
      labels:
        app: "rest2"
    spec:
      containers:
      - name: "kube-learning-sha256-1"
        image: "gcr.io/kubernetes-learning-304123/rest2:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: rest2-service
spec:
  selector:
    app: rest2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer