---
######## INSTALL BASE ########

- hosts: k8s
  become: true
  gather_facts: false
  
  roles:
    - base


######## INSTALL DOCKER + K8S ########

- hosts: nodes
  become: true
  gather_facts: false
  roles:
    - docker
    - kubernetes


######## INSTALL HELM ########

- hosts: masters
  become: true
  gather_facts: false
  roles:
    - helm


# ######## INSTALL AND MOUNT NFS SHARES ########

# # - hosts: workers
# #   become: true
# #   gather_facts: false

# #   tasks:
# #     - name: Install nfs-common
# #       package:
# #         name: nfs-common
# #         state: 'latest'

# #     - name: Create a mountable directory
# #       file:
# #         path: /mnt/bob-cached
# #         state: directory
# #         mode: '0755'

# #     - name: Mount volume and mount on boot
# #       shell: |
# #         echo "bob.psilva.org:/mnt/user/k8scached /mnt/bob-cached nfs defaults 0 0" >> /etc/fstab
# #         mount -av


######## SETUP LOAD BALANCER ########

- hosts: kloadbalancers
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/kloadbalancer-setup.yml


####### INSTALL INITIALIZE MASTER 1 ########

- hosts: kmaster1
  become: true
  gather_facts: false

  tasks:
    - include_tasks: tasks/control-plane-setup.yml


####### CLEAN UP ########
- hosts: k8s
  become: true

  tasks:
    - name: "clean cache"
      command: apt-get clean
      when: ansible_distribution in ['Debian', 'Ubuntu']
