---
######## INSTALL BASE ########

- hosts: k8s
  become: true
  gather_facts: false
  
  roles:
    - base


- hosts: kloadbalancers
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/kloadbalancer-setup.yml


######## INSTALL DOCKER + K8S ########

- hosts: nodes
  become: true
  gather_facts: false
  roles:
    - docker
    - kubernetes


######## INSTALL HELM ########

- hosts: masters
  become: true
  gather_facts: false
  roles:
    - helm
    # install istio binaries here




####### INSTALL INITIALIZE MASTER 1 ########

- hosts: kmaster1
  become: true
  gather_facts: false

  tasks:
    - include_tasks: tasks/control-plane-setup.yml
  tags:
    - control_plane



####### INSTALL OTHER MASTERS ########

- hosts: kmaster1
  become: true
  gather_facts: false

  tasks:

    - name: Get master join command
      command: >
        bash -c "grep -A 3 'kubeadm join' /root/kube-join.txt | head -3 | tr '\\\\\t\n' ' '"
      register: master_join
      tags:
        - masters_join

    - name: Get worker join command
      command: >
        bash -c "grep -A 3 'kubeadm join' /root/kube-join.txt | tail -2 | tr '\\\\\t\n' ' '"
      register: worker_join
      tags:
        - worker_join

    - name: create masters script
      become: false
      copy:
        content: "{{ master_join.stdout }}"
        dest: "/tmp/master.sh"
      delegate_to: localhost
      tags:
        - masters_join

    - name: create workers script
      become: false
      copy:
        content: "{{ worker_join.stdout }}"
        dest: "/tmp/worker.sh"
      delegate_to: localhost
      tags:
        - worker_join


- hosts: kmaster2
  become: true
  gather_facts: false
  tasks:
    - name: Copy and execute master script 
      script: /tmp/master.sh
      tags:
        - masters_join

- hosts: workers
  become: true
  gather_facts: false
  tasks:
    - name: Copy and execute worker script 
      script: /tmp/worker.sh
      tags:
        - worker_join


- hosts: localhost
  gather_facts: false
  tasks:
    - name: Clean Ansible local scripts
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/master.sh
        - /tmp/worker.sh
      tags:
        - local_clean


- hosts: kmaster1
  become: true
  gather_facts: false
  tasks:
    - name: Install istio
      command: "{{ item }}"
      with_items:
        - wget -O istio_install.sh https://git.io/getLatestIstio
        - bash ./istio_install.sh ; false
        - find . -name 'istioctl' -exec cp "{}" /usr/bin  \;
        - istioctl install --skip-confirmation
        #- kubectl label namespace default istio-injection=enabled
        - bash -c "rm -rf istio*"
      tags:
        - istio
    


####### CLEAN UP ########
- hosts: k8s
  become: true

  tasks:
    - name: "clean cache"
      command: apt-get clean
      when: ansible_distribution in ['Debian', 'Ubuntu']
