---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    env: develop
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-role
  namespace: jenkins
  labels:
    env: develop

---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: jenkins-account
 namespace: jenkins
  labels:
    env: develop

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: jenkins
  labels:
    env: develop