---
# NEED TO FIX THIS TO WORK WITH DEV AND PROD
- name: Initialize Kubernetes master with kubeadm init
  command: >
    kubeadm init \
    --pod-network-cidr=10.200.0.0/16 \
  #  --upload-certs \
    --control-plane-endpoint={{control_plane_endpoint}}
  register: kubeadmin_init
  tags:
    - kube_init
    - master_init


- name: Print the init output to screen.
  debug:
    var: kubeadmin_init.stdout
  tags:
    - kube_init
  when: 
    - kubeadmin_init.stdout is defined

- name: Save output to ~/kube-join.txt
  copy: content="{{ kubeadmin_init.stdout }}" dest=~/kube-join.txt
  tags:
    - kube_init
  when: 
      - kubeadmin_init.stdout is defined

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755
  tags:
    - kube_config

- name: Copy kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    mode: u=rwx,g=rx,o=rx  # 755
    remote_src: true
  tags:
    - kube_config
  when: 
    - kubeadmin_init.stdout is defined
