---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3
  labels:
    app: iperf3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          command: ["iperf3"]
          args: ["-s"]
          ports:
            - containerPort: 5201
          resources:
            limits:
              memory: 400Mi
              cpu:  800m
            requests:
              memory: 200Mi
              cpu: 400m

---
apiVersion: v1
kind: Service
metadata:
  name: iperf3
spec:
  selector:
    app: iperf3
  ports:
    - port: 5201
      targetPort: 5201
  type: LoadBalancer
  loadBalancerIP: 192.168.50.41
