apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-nfs
provisioner: example.com/external-nfs
parameters:
  server: bob.psilva.org
  path: /mnt/user/k8scached
  readOnly: "false"