apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-account
      securityContext:
        fsGroup: 1000
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50000
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 10
          volumeMounts:
            - name: nfs-pvc
              mountPath: /var/jenkins_home
          resources:
            limits:
              cpu: 800m
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 3Gi
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: jenkins-claim
