---
apiVersion: v1
kind: Namespace
metadata:
  name: iperf3-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3
  namespace: iperf3-ns
  labels:
    app: iperf3
    categ: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
        categ: tools
    spec:
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          command: ["iperf3"]
          args: ["-s"]
          ports:
            - containerPort: 5201
          resources:
            limits:
              memory: 30Mi
              cpu:  600m
            requests:
              memory: 10Mi
              cpu: 300m

---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-svc
  namespace: iperf3-ns
  labels:
    app: iperf3
    categ: tools
spec:
  selector:
    app: iperf3
  ports:
    - port: 5201
      targetPort: 5201
  type: LoadBalancer
  loadBalancerIP: 192.168.51.100
