---
- hosts: master1
  gather_facts: no

  vars:
    service_name: k8_master1

  tasks:
    - name: Copy profile yaml to server
      ansible.builtin.copy:
        src: "files" 
        dest: /tmp/{{ service_name }}.d/

    - name: Create resolved folder 
      file:
        path: /hdd-pool/appdata/{{ service_name }}-lxd/resolved.conf.d/
        state: directory

    - name: Create appdata folder 
      file:
        path: /hdd-pool/appdata/{{ service_name }}-lxd/AdGuardHome/
        state: directory


    - name: "Create {{ service_name }} server container"
      command: "{{ item }}"
      loop:
        - lxc profile create {{ service_name }}
        - bash -c "cat /tmp/{{ service_name }}.d/files/{{ service_name }}-profile.yml | lxc profile edit {{ service_name }}"
        - lxc init -p conf-autostart-on.yml -p disk-std.yml -p network-lvl1.yml -p {{ service_name }} images:ubuntu/focal/cloud  {{ service_name }}
        - lxc config set {{ service_name }} limits.cpu 2
        - lxc config set {{ service_name }} limits.memory 2GB
        - lxc start {{ service_name }}

    - name: Delete files 
      file:
        state: absent
        path: "/tmp/adguard.d"
        
