steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/rest1:latest'
  - '--file=apps/rest1/Dockerfile'
  - 'apps/rest1/'

images: ['gcr.io/$PROJECT_ID/rest1:latest']

