---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rest1"
  namespace: "default"
  labels:
    app: "rest1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "rest1"
  template:
    metadata:
      labels:
        app: "rest1"
    spec:
      containers:
      - name: "kube-learning-sha256-1"
        image: "ghcr.io/gasilva-clgx/rest1"
---
apiVersion: v1
kind: Service
metadata:
  name: rest1-service
spec:
  selector:
    app: rest1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer