---

- name: Install required system packages
  package: name={{ item }} state=latest update_cache=yes 
  loop: ['ca-certificates', 'curl', 'lsb-release', 'gnupg2']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Fetch lsb_release -cs
  shell: lsb_release -cs
  register: lsb_rel

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install Docker
  apt:
    update_cache: yes
    state: latest
    name: '{{ item }}'
  loop:
    #- containerd.io 
    - docker-ce
    - docker-ce-cli

- name: Create required directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/systemd/system/docker.service.d
    - /etc/docker

- name: creates /etc/docker/daemon.json
  ansible.builtin.file:
    path: /etc/docker/daemon.json
    state: touch   

- name: Create daemon json config file
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    line: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Restart Docker
  service: name=docker state=restarted

- name: Clean apt cache
  command:
    cmd: apt-get clean

- name: Ensure group "docker" 
  ansible.builtin.group:
    name: docker
    state: present

- name: adding existing user '{{ ansible_ssh_user }}' to group docker
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes