---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: httptls
      port: 443
      targetPort: 8443
    - name: http
      port: 80
      targetPort: 8080
    - name: agents 
      port: 50000
      targetPort: 50000
  type: LoadBalancer
  loadBalancerIP: 192.168.50.42
