---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  namespace: jenkins
  labels:
    env: prod
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: bob.psilva.org
    path: "/mnt/user/k8scached/jenkins-pv"

