---

######## INSTALL BASE ########

- hosts: nodes
  become: true
  gather_facts: false
  tags:
    - base
  roles:
    - base


- hosts: loadbalancers
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/kloadbalancer-setup.yml
      when: false # only sbx env is set for a high availability setup



####### INSTALL DOCKER + K8S ########

- hosts: nodes
  become: true
  gather_facts: false
  tags:
    - cluster_member
  roles:
    - crio
    - kubernetes


######## INSTALL HELM ########

- hosts: masters
  become: true
  gather_facts: false
  tags:
    - helm
  roles:
    - helm
    # install istio binaries here


####### INSTALL INITIALIZE MASTER 1 ########

- hosts: master1
  become: true
  gather_facts: true
  tags:
    - control_plane
  tasks:
    - include_vars: "{{vars_file}}"
    - include_tasks: tasks/control-plane-setup.yml


####### All join the cluster  #######
- name: Include a play after another play
  import_playbook: nodes-join.yml


####### INSTALL COMPONENTS ########

- hosts: master1
  become: true
  gather_facts: true
  tags:
    - control_plane_components
  tasks:
    - include_vars: "{{vars_file}}"
    - include_tasks: tasks/control-plane-components.yml


# - hosts: master1
#   become: true
#   gather_facts: false
#   tasks:
#     - name: Install istio
#       command: "{{ item }}"
#       with_items:
#         - wget -O istio_install.sh https://git.io/getLatestIstio
#         - bash ./istio_install.sh ; false
#         - find . -name 'istioctl' -exec cp "{}" /usr/bin  \;
#         - istioctl install --skip-confirmation
#         #- kubectl label namespace default istio-injection=enabled
#         - bash -c "rm -rf istio*"
#       tags:
#         - istio
    


####### CLEAN UP ########
- hosts: k8s
  become: true
  serial: 1

  tasks:
    - name: "clean cache"
      command: apt-get clean
      when: ansible_distribution in ['Debian', 'Ubuntu']
