version: '3.2'

services:

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - TZ=America/Toronto

  node-exporter:
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'
    environment:
      - TZ=America/Toronto

  cadvisor:
    image: justrobin/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/disk/:/dev/disk:ro
    environment:
      - TZ=America/Toronto
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml 
      #- --web.config.file=/etc/prometheus/auth.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./auth.yml:/etc/prometheus/auth.yml:ro
    environment:
      - TZ=America/Toronto
    depends_on:
    - cadvisor