---

######## CREATE ALL NODES ########

- hosts: captain
  gather_facts: false

  tasks:
    - name: Provision Load Balancer
      include_tasks: tasks/server.yml
      vars:
        - name: '{{spec.name}}'
          cpus: '{{spec.cpus}}'
          mem: '{{spec.mem}}'
          disk: '{{spec.disk}}'
          ip: '{{spec.ip}}'
          as_vm: '{{spec.as_vm}}'
          force_destroy: '{{spec.force_destroy}}'
          skip: '{{spec.skip}}'

      loop:
        - name: kloadbalancer1
          cpus: 1
          mem: 1GB
          disk: 4GB
          ip: 192.168.50.20
          as_vm: false
          skip: false
          force_destroy: false

        - name: kmaster1
          cpus: 2
          mem: 2GB
          disk: 4GB
          ip: 192.168.50.21
          as_vm: true
          skip: false
          force_destroy: false

        - name: kmaster2
          cpus: 2
          mem: 2GB
          disk: 4GB
          ip: 192.168.50.22
          as_vm: true
          skip: false
          force_destroy: false

        - name: knode1
          cpus: 1
          mem: 1GB
          disk: 4GB
          ip: 192.168.50.31
          as_vm: true
          skip: false
          force_destroy: false

        - name: knode2
          cpus: 2
          mem: 2GB
          disk: 4GB
          ip: 192.168.50.32
          as_vm: true
          skip: false
          force_destroy: false

        - name: knode3
          cpus: 4
          mem: 8GB
          disk: 4GB
          ip: 192.168.50.33
          as_vm: true
          skip: false
          force_destroy: false

        - name: knode4
          cpus: 8
          mem: 10GB
          disk: 4GB
          ip: 192.168.50.34
          as_vm: true
          skip: false
          force_destroy: false

      loop_control:
        loop_var: spec

    - name: Pause to initialize the containers
      shell: sleep 60
      delegate_to: 127.0.0.1


######## INSTALL BASE ########

- hosts: k8s
  become: true
  gather_facts: false
  
  roles:
    - base


######## INSTALL DOCKER + K8S ########

- hosts: nodes
  become: true
  gather_facts: false
  roles:
    - docker
    - kubernetes


######## INSTALL HELM ########

- hosts: masters
  become: true
  gather_facts: false
  roles:
    - helm


######## INSTALL AND MOUNT NFS SHARES ########

# - hosts: workers
#   become: true
#   gather_facts: false

#   tasks:
#     - name: Install nfs-common
#       package:
#         name: nfs-common
#         state: 'latest'

#     - name: Create a mountable directory
#       file:
#         path: /mnt/bob-cached
#         state: directory
#         mode: '0755'

#     - name: Mount volume and mount on boot
#       shell: |
#         echo "bob.psilva.org:/mnt/user/k8scached /mnt/bob-cached nfs defaults 0 0" >> /etc/fstab
#         mount -av


######## SETUP LOAD BALANCER ########

- hosts: kloadbalancers
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/kloadbalancer-setup.yml


####### INSTALL INITIALIZE MASTER 1 ########

- hosts: kmaster1
  become: true
  gather_facts: false

  tasks:
    - include_tasks: tasks/control-plane-setup.yml


####### CLEAN UP ########
- hosts: k8s
  become: true

  tasks:
    - name: "clean cache"
      command: apt-get clean
      when: ansible_distribution in ['Debian', 'Ubuntu']
