- hosts: kmaster1
  become: true

  tasks:

    - name: Initialize Kubernetes master with kubeadm init
      command: >
        kubeadm init \
        --pod-network-cidr=192.168.0.0/16 \
        --upload-certs \
        --control-plane-endpoint=k8s-cluster.psilva.org
      register: kubeadmin_init

    - name: Print the init output to screen.
      debug:
        var: kubeadmin_init.stdout

    - name: Save output to ~/kube-join.txt
      copy: content="{{ kubeadmin_init.stdout }}" dest=~/kube-join.txt

    - name: Ensure .kube directory exists.
      file:
        path: ~/.kube
        state: directory
        mode: 0755

    - name: Symlink the kubectl admin.conf to ~/.kube/conf.
      file:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        state: link
        mode: 0644

    - name: Configure Calico networking.
      command: "{{ item }}"
      with_items:
        - kubectl apply -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
        - kubectl apply -f https://docs.projectcalico.org/manifests/custom-resources.yaml
      register: calico_result
      changed_when: "'created' in calico_result.stdout"
