---
- hosts: captain
  gather_facts: no

  tasks:
    - name: Copy cloud-init profile yaml to server
      ansible.builtin.copy:
        src: "files" 
        dest: /tmp/{{name}}.d/

    - name: Edit node server name
      ansible.builtin.replace:
        path: /tmp/{{name}}.d/files/cloud-init.yml
        regexp: 'master1'
        replace: "{{name}}"

    - name: Edit node IP
      ansible.builtin.replace:
        path: /tmp/{{name}}.d/files/cloud-init.yml
        regexp: '192.168.50.21'
        replace: "{{ip}}"

    - name: "Create {{name}} server container"
      command: "{{ item }}"
      loop:
        - lxc profile create {{name}}
        - bash -c "cat /tmp/{{name}}.d/files/cloud-init.yml | lxc profile edit {{name}}"
        - lxc init images:ubuntu/focal/cloud {{name}}
        - lxc config device add {{name}} root disk path=/ pool=default size={{disk}} 
        - lxc config device add {{name}} eth0 nic nictype=bridged parent=br0 name=eth0
        - lxc profile add {{name}} {{name}}
        - lxc profile remove {{name}} default
        - lxc config set {{name}} limits.cpu {{cpus}}
        - lxc config set {{name}} limits.memory {{mem}}
        - lxc start {{name}}

    - name: Delete files 
      file:
        state: absent
        path: "/tmp/{{name}}.d"
        
