---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-lb
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: httptls
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
    - name: agents 
      port: 50000
      targetPort: 50000
  type: LoadBalancer
  loadBalancerIP: 192.168.51.151
