---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: iperf3
          image: nginx
          ports:
            - containerPort: 5201
          resources:
            limits:
              memory: 200Mi
              cpu:  100m
            requests:
              memory: 100Mi
              cpu: 100m